version: 2
models:
- name: contributors
  description: A single table containing all authors and committers as contributors.

  tests:
    - unique:
        column_name: "concat(contributor_name, '-', contributor_email)"

  columns:
    - name: contributor_name
      description: The git username of a user.

    - name: contributor_email
      description: The git email address of the user.

- name: repositories
  description: All the repositories known in the dataset.

  columns:
    - name: repository_name
      description: The name of the repository, in the form of 'owner/repository'.
      tests:
        - unique
        - not_null

    - name: license_name
      description: The license associated with the repository. Some repositories do not have licenses.
